# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-24 21:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cryptocurrency',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('number_of_coins', models.IntegerField()),
                ('purchase_price', models.FloatField()),
                ('date_purchased', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('street', models.TextField()),
                ('state', models.CharField(max_length=2)),
                ('zip', models.CharField(max_length=5)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=11)),
            ],
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('symbol', models.CharField(max_length=5)),
                ('name', models.TextField()),
                ('number_of_shares', models.IntegerField()),
                ('purchase_price', models.FloatField()),
                ('date_purchased', models.DateTimeField(blank=True, null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='financial.Customer')),
            ],
        ),
        migrations.AddField(
            model_name='cryptocurrency',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='financial.Customer'),
        ),
    ]
