# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-25 02:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0002_auto_20180224_1735'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock',
            name='symbol',
        ),
        migrations.AddField(
            model_name='cryptocurrency',
            name='symbol',
            field=models.CharField(default=django.utils.timezone.now, max_length=5),
            preserve_default=False,
        ),
    ]
